<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GccPhat.RealTime.Shared\GccPhat.RealTime.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="PortAudioSharp2" Version="1.0.6" />
  </ItemGroup>

</Project>
